#!/usr/bin/env bash

# Automatically exit script on error
set -e

# Defaults
jobspec=""
multiplier=1
num_sims_in_jobspec=100

function print_help() {
  echo "Usage:"
  echo "  `basename $0` [OPTIONS] <JOBSPEC>"
  echo
  echo "Options:"
  echo "  -h    Print this help"
  echo "  -n    Number of sims in the jobspec (Default=$num_sims_in_jobspec)"
  echo "  -m    Number of times to run the jobspec (Default=$multiplier)"
}

while getopts ":m:n:h" opt; do
  case $opt in
    m)
      multiplier=${OPTARG}
      ;;
    n)
      num_sims_in_jobspec=${OPTARG}
      ;;
    h)
      print_help
      exit
      ;;
    :)
      echo -e "ERROR: Option -${OPTARG} requires an argument\n" >&2
      print_help
      exit 1
      ;;
    \?)
      echo -e "ERROR: Invalid option: -${OPTARG}\n" >&2
      print_help
      exit 1
      ;;
  esac
done

# Remove all option arguments and leave "$@" with just the non-option arguments
shift $((OPTIND-1))

if (( $# == 0 )); then
  echo -e "ERROR: Jobspec not specified\n" >&2
  print_help
fi
jobspec="$1"

batch=0
while (( $batch < $multiplier )); do
  if (( $(lsf_bjobs | wc -l) < $(( 975 - $num_sims_in_jobspec )) )); then
    ~kshenoy/bin/rerun -f ${jobspec} &
    ((++batch));
  fi;

  sleep 300;
done
