# Local ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# Kartik Shenoy (kartik.shenoy@amd.com)
#
# This file is used only for local settings
export TZ="US/Mountain"

# fzf: https://github.com/junegunn/fzf
[[ -d $HOME/.local/install/fzf ]] && export FZF_PATH="$HOME/.local/install/fzf"

# To help load pandora modules. This also puts the pandora binaries in the path
. /proj/verif_release_ro/cbwa_initscript/nodisk_current/cbwa_init.bash

# See http://cmdwww/sysadmin/modules for more information
# module load <vendorname>/[version]
# module list - to look at loaded modules
# module avail <package> - to see different versions of the package eg. `module avail emacs`
module load hdk-6/1.1
module load ctags/4518
module load emacs/25.1
module load git/2.16.2
module load the_silver_searcher/2.1.0
module load tmux/2.7
module load util-linux/2.23 2> /dev/null
module load vim/8.0-c
module load xterm/326

complete -f -o default -X '!*.xml' ljd
complete -f -o default -X '!*.vv' vv

# This is needed to display the terminal characters correctly : /
# Loading the HDK resets LANG=C which causes font rendering issues in xterm so putting it after the module load
# Update - I'm starting xterm by passing it `-en en_US.UTF-8` instead of forcing LANG as that has other side-effects
# export LANG=en_US.UTF-8
